Nohref checks (#293)
* Fixed "error C4996: 'GetVersionExA': was declared deprecated" using a crutch.
* Added NOXREFCHECK to all NOXREF functions.
* Removed NOXREF from Sys_CheckOSVersion because it is being called.